version: '3'
services:
  php-fpm:
    image: jkaninda/laravel-php-fpm:8.3
    container_name: laravel1
    restart: unless-stopped     
    volumes:
    #Project root
        - ./laravel:/var/www/html
    networks:
        - some-network #if you're using networks between containers
  php-fpm2:
    image: jkaninda/laravel-php-fpm:8.3
    container_name: laravel2
    restart: unless-stopped     
    volumes:
    #Project root
        - ./laravel2:/var/www/html
    networks:
        - some-network #if you're using networks between containers

    #Nginx server
  nginx-server1:
    build: 
      context: ./nginx/src/
      dockerfile: Dockerfile
      args:
        PORT: 81
    container_name: laravel1-nginx
    restart: unless-stopped
    ports:
    - 8081:81
    volumes:
    - ./laravel:/var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - CLIENT_MAX_BODY_SIZE=20M
      - PHP_FPM_HOST=php-fpm:9000
      - PORT=81
    networks:
    - some-network
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`laravel1.localhost`)"
      - "traefik.port=8081"

  nginx-server2:
    build: 
      context: ./nginx/src/
      dockerfile: Dockerfile
      args:
        PORT: 82
    container_name: laravel2-nginx
    restart: unless-stopped
    ports:
    - 8082:82
    volumes:
    - ./laravel2:/var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - CLIENT_MAX_BODY_SIZE=20M
      - PHP_FPM_HOST=php-fpm:9000
    networks:
    - some-network
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`laravel2.localhost`)"
      - "traefik.port=8082"


  reverse-proxy:
    image: traefik:v2.10

    command: --api.insecure=true --providers.docker

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    networks:
      - some-network
        
networks:
  some-network:
   driver: bridge